version: '3.4'

services:
  loginservice:
    image: loginsvc
    build:
      context: .
      dockerfile: LoginMS.Web/Dockerfile
    ports:
    - 32001:80

  vikleservice:
    image: vikleapisvc
    build:
      context: .
      dockerfile: VikleAPIMS.Web/Dockerfile
    ports:
    - 32002:80