version: '3.4'

services:
  customerservice:
    image: loginsvc
    build:
      context: .
      dockerfile: Customers.Web/Dockerfile
    ports:
    - 32001:80

  orderservice:
    image: vikleapisvc
    build:
      context: .
      dockerfile: Orders.Web/Dockerfile
    ports:
    - 32002:80