version: '3.4'

services:
  loginservice:
    image: loginsvc
    restart: on-failure
    links:
      - mongodb
      - kafkaserver
    depends_on:
      - kafkaserver
    build:
      context: .
      dockerfile: LoginMS.Web/Dockerfile
    ports:
    - 32001:80

  vikleservice:
    image: vikleapisvc
    restart: on-failure
    links:
      - mongodb
      - kafkaserver
    depends_on:
      - kafkaserver
    build:
      context: .
      dockerfile: VikleAPIMS.Web/Dockerfile
    ports:
      - "32002:80"
      
  gatewayservice:
    image: gatewaysvc
    build:
      context: .
      dockerfile: GatewayMS/Dockerfile
    ports:
    - 32003:80
      
  kafkaserver:
    image: "spotify/kafka:latest"
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    depends_on:
      - mongodb
    ports:
      - "8081:8081"