version: '3.4'

services:
  loginservice:
    image: loginsvc
    build:
      context: .
      dockerfile: LoginMS.Web/Dockerfile
    ports:
    - 32001:32001

  vikleservice:
    image: vikleapisvc
    build:
      context: .
      dockerfile: VikleAPIMS.Web/Dockerfile
    ports:
    - 32002:32002
      
  gatewayservice:
    image: gatewaysvc
    build:
      context: .
      dockerfile: GatewayMS/Dockerfile
    ports:
    - 32003:80